Social Network Ads Dataset Decision Tree

In [5]:
print("Hello world")

Hello world

In [6]:
import pandas as pd

In [7]:
# Age is in a differen scale than estimated salary. Thus we need to convert them into a standard scale.

In [8]:
df = pd.read_csv(r"D:\msis-labs\msis-labs\aml-lab\projects\data\Social_Network_Ads.csv")

In [9]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [10]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [11]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
x = df.iloc[:, 2:4].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],
       [    27,  58000],
       [    24,  55000],
       [    23,  48000],
       [    28,  79000],
       [    22,  18000],
       [    32, 117000],
       [    27,  20000],
       [    25,  87000],
       [    23,  66000],
       [    32, 120000],
       [    59,  83000],
       [    24,  58000],
       [    24,  19000],
       [    23,  82000],
       [    22,  63000],
       [    31,  68000],
       [    25,  80000],
       [    24,  27000],
       [    20,  23000],
       [    33, 113000],
       [    32,  18000],
       [    34, 112000],
       [    18,  52000],
       [    22,  27000],
       [    28,  87000],
       [    26,  17000],
       [    30,  80000],
       [    39,  42000],
       [    20,  49000],
       [    35,  88000],
       [    30,  62000],
       [    31, 118000],
       [    24,  55000],
       [    28,  85000],
       [    26,  81000],
       [    35,  50000],
       [    22,  81000],
       [    30, 116000],
       [    26,  15000],
       [    29,  28000],
       [    29,  83000],
       [    35,  44000],
       [    35,  25000],
       [    28, 123000],
       [    35,  73000],
       [    28,  37000],
       [    27,  88000],
       [    28,  59000],
       [    32,  86000],
       [    33, 149000],
       [    19,  21000],
       [    21,  72000],
       [    26,  35000],
       [    27,  89000],
       [    26,  86000],
       [    38,  80000],
       [    39,  71000],
       [    37,  71000],
       [    38,  61000],
       [    37,  55000],
       [    42,  80000],
       [    40,  57000],
       [    35,  75000],
       [    36,  52000],
       [    40,  59000],
       [    41,  59000],
       [    36,  75000],
       [    37,  72000],
       [    40,  75000],
       [    35,  53000],
       [    41,  51000],
       [    39,  61000],
       [    42,  65000],
       [    26,  32000],
       [    30,  17000],
       [    26,  84000],
       [    31,  58000],
       [    33,  31000],
       [    30,  87000],
       [    21,  68000],
       [    28,  55000],
       [    23,  63000],
       [    20,  82000],
       [    30, 107000],
       [    28,  59000],
       [    19,  25000],
       [    19,  85000],
       [    18,  68000],
       [    35,  59000],
       [    30,  89000],
       [    34,  25000],
       [    24,  89000],
       [    27,  96000],
       [    41,  30000],
       [    29,  61000],
       [    20,  74000],
       [    26,  15000],
       [    41,  45000],
       [    31,  76000],
       [    36,  50000],
       [    40,  47000],
       [    31,  15000],
       [    46,  59000],
       [    29,  75000],
       [    26,  30000],
       [    32, 135000],
       [    32, 100000],
       [    25,  90000],
       [    37,  33000],
       [    35,  38000],
       [    33,  69000],
       [    18,  86000],
       [    22,  55000],
       [    35,  71000],
       [    29, 148000],
       [    29,  47000],
       [    21,  88000],
       [    34, 115000],
       [    26, 118000],
       [    34,  43000],
       [    34,  72000],
       [    23,  28000],
       [    35,  47000],
       [    25,  22000],
       [    24,  23000],
       [    31,  34000],
       [    26,  16000],
       [    31,  71000],
       [    32, 117000],
       [    33,  43000],
       [    33,  60000],
       [    31,  66000],
       [    20,  82000],
       [    33,  41000],
       [    35,  72000],
       [    28,  32000],
       [    24,  84000],
       [    19,  26000],
       [    29,  43000],
       [    19,  70000],
       [    28,  89000],
       [    34,  43000],
       [    30,  79000],
       [    20,  36000],
       [    26,  80000],
       [    35,  22000],
       [    35,  39000],
       [    49,  74000],
       [    39, 134000],
       [    41,  71000],
       [    58, 101000],
       [    47,  47000],
       [    55, 130000],
       [    52, 114000],
       [    40, 142000],
       [    46,  22000],
       [    48,  96000],
       [    52, 150000],
       [    59,  42000],
       [    35,  58000],
       [    47,  43000],
       [    60, 108000],
       [    49,  65000],
       [    40,  78000],
       [    46,  96000],
       [    59, 143000],
       [    41,  80000],
       [    35,  91000],
       [    37, 144000],
       [    60, 102000],
       [    35,  60000],
       [    37,  53000],
       [    36, 126000],
       [    56, 133000],
       [    40,  72000],
       [    42,  80000],
       [    35, 147000],
       [    39,  42000],
       [    40, 107000],
       [    49,  86000],
       [    38, 112000],
       [    46,  79000],
       [    40,  57000],
       [    37,  80000],
       [    46,  82000],
       [    53, 143000],
       [    42, 149000],
       [    38,  59000],
       [    50,  88000],
       [    56, 104000],
       [    41,  72000],
       [    51, 146000],
       [    35,  50000],
       [    57, 122000],
       [    41,  52000],
       [    35,  97000],
       [    44,  39000],
       [    37,  52000],
       [    48, 134000],
       [    37, 146000],
       [    50,  44000],
       [    52,  90000],
       [    41,  72000],
       [    40,  57000],
       [    58,  95000],
       [    45, 131000],
       [    35,  77000],
       [    36, 144000],
       [    55, 125000],
       [    35,  72000],
       [    48,  90000],
       [    42, 108000],
       [    40,  75000],
       [    37,  74000],
       [    47, 144000],
       [    40,  61000],
       [    43, 133000],
       [    59,  76000],
       [    60,  42000],
       [    39, 106000],
       [    57,  26000],
       [    57,  74000],
       [    38,  71000],
       [    49,  88000],
       [    52,  38000],
       [    50,  36000],
       [    59,  88000],
       [    35,  61000],
       [    37,  70000],
       [    52,  21000],
       [    48, 141000],
       [    37,  93000],
       [    37,  62000],
       [    48, 138000],
       [    41,  79000],
       [    37,  78000],
       [    39, 134000],
       [    49,  89000],
       [    55,  39000],
       [    37,  77000],
       [    35,  57000],
       [    36,  63000],
       [    42,  73000],
       [    43, 112000],
       [    45,  79000],
       [    46, 117000],
       [    58,  38000],
       [    48,  74000],
       [    37, 137000],
       [    37,  79000],
       [    40,  60000],
       [    42,  54000],
       [    51, 134000],
       [    47, 113000],
       [    36, 125000],
       [    38,  50000],
       [    42,  70000],
       [    39,  96000],
       [    38,  50000],
       [    49, 141000],
       [    39,  79000],
       [    39,  75000],
       [    54, 104000],
       [    35,  55000],
       [    45,  32000],
       [    36,  60000],
       [    52, 138000],
       [    53,  82000],
       [    41,  52000],
       [    48,  30000],
       [    48, 131000],
       [    41,  60000],
       [    41,  72000],
       [    42,  75000],
       [    36, 118000],
       [    47, 107000],
       [    38,  51000],
       [    48, 119000],
       [    42,  65000],
       [    40,  65000],
       [    57,  60000],
       [    36,  54000],
       [    58, 144000],
       [    35,  79000],
       [    38,  55000],
       [    39, 122000],
       [    53, 104000],
       [    35,  75000],
       [    38,  65000],
       [    47,  51000],
       [    47, 105000],
       [    41,  63000],
       [    53,  72000],
       [    54, 108000],
       [    39,  77000],
       [    38,  61000],
       [    38, 113000],
       [    37,  75000],
       [    42,  90000],
       [    37,  57000],
       [    36,  99000],
       [    60,  34000],
       [    54,  70000],
       [    41,  72000],
       [    40,  71000],
       [    42,  54000],
       [    43, 129000],
       [    53,  34000],
       [    47,  50000],
       [    42,  79000],
       [    42, 104000],
       [    59,  29000],
       [    58,  47000],
       [    46,  88000],
       [    38,  71000],
       [    54,  26000],
       [    60,  46000],
       [    60,  83000],
       [    39,  73000],
       [    59, 130000],
       [    37,  80000],
       [    46,  32000],
       [    46,  74000],
       [    42,  53000],
       [    41,  87000],
       [    58,  23000],
       [    42,  64000],
       [    48,  33000],
       [    44, 139000],
       [    49,  28000],
       [    57,  33000],
       [    56,  60000],
       [    49,  39000],
       [    39,  71000],
       [    47,  34000],
       [    48,  35000],
       [    48,  33000],
       [    47,  23000],
       [    45,  45000],
       [    60,  42000],
       [    39,  59000],
       [    46,  41000],
       [    51,  23000],
       [    50,  20000],
       [    36,  33000],
       [    49,  36000]])

In [14]:
y = df.iloc[:, -1].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1])

In [15]:
import numpy as np

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=45)

In [17]:
x_test.astype(int)

array([[    52,  90000],
       [    53,  72000],
       [    40,  72000],
       [    57,  33000],
       [    40,  61000],
       [    19,  21000],
       [    32,  86000],
       [    35,  72000],
       [    25,  87000],
       [    59,  29000],
       [    29,  75000],
       [    45,  79000],
       [    24,  32000],
       [    56,  60000],
       [    39,  42000],
       [    19,  76000],
       [    26,  72000],
       [    47,  20000],
       [    18,  52000],
       [    20,  23000],
       [    37,  79000],
       [    55, 125000],
       [    35,  55000],
       [    40,  75000],
       [    29,  61000],
       [    18,  68000],
       [    29, 148000],
       [    25,  90000],
       [    47,  23000],
       [    38,  61000],
       [    43, 112000],
       [    40,  57000],
       [    59,  42000],
       [    26, 118000],
       [    35,  75000],
       [    45,  22000],
       [    26,  80000],
       [    35,  97000],
       [    20,  36000],
       [    60,  42000],
       [    24,  23000],
       [    46, 117000],
       [    43, 129000],
       [    49, 141000],
       [    29,  83000],
       [    37, 144000],
       [    58,  47000],
       [    59,  88000],
       [    31,  68000],
       [    38,  51000],
       [    46,  59000],
       [    30,  87000],
       [    47,  34000],
       [    48,  74000],
       [    40,  75000],
       [    41,  80000],
       [    42,  73000],
       [    35,  25000],
       [    32, 120000],
       [    44, 139000],
       [    21,  88000],
       [    34,  43000],
       [    49,  39000],
       [    27,  57000],
       [    28,  37000],
       [    49,  89000],
       [    28,  44000],
       [    30,  17000],
       [    22,  55000],
       [    56, 104000],
       [    23,  20000],
       [    40,  57000],
       [    24,  89000],
       [    38,  65000],
       [    40, 142000],
       [    52, 138000],
       [    33, 113000],
       [    26,  17000],
       [    48,  33000],
       [    58, 101000],
       [    21,  68000],
       [    36, 126000],
       [    44,  39000],
       [    25,  22000],
       [    20,  74000],
       [    34,  72000],
       [    39,  59000],
       [    55,  39000],
       [    39,  61000],
       [    37,  70000],
       [    42,  90000],
       [    19,  25000],
       [    47, 107000],
       [    39,  79000],
       [    35,  57000],
       [    25,  79000],
       [    58,  38000],
       [    30, 116000],
       [    40,  59000],
       [    27,  54000]])

In [18]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [19]:
x_train

array([[ 0.42118245,  0.15177847],
       [-1.86353366, -1.48066604],
       [ 0.81852438, -1.10170571],
       [-0.17483045, -0.46038822],
       [-0.27416593,  0.61819119],
       [ 1.71254373,  1.75507219],
       [-0.67150786,  0.12262768],
       [ 0.22251148, -0.28548345],
       [ 1.01719535, -0.83934855],
       [-0.07549497,  0.23923086],
       [ 0.42118245, -0.46038822],
       [ 0.32184696, -0.51868981],
       [-0.07549497,  0.12262768],
       [-0.67150786, -1.04340412],
       [-1.16818528,  0.41413563],
       [ 1.11653083, -0.98510253],
       [ 1.11653083, -0.13972948],
       [ 1.21586631, -1.45151524],
       [ 2.10988566,  0.18092927],
       [-0.77084335,  0.29753245],
       [-1.16818528,  0.47243721],
       [-0.96951431, -0.31463425],
       [-0.17483045, -0.19803107],
       [-0.87017883, -0.78104696],
       [-0.57217238, -1.50981683],
       [-0.37350142, -0.78104696],
       [ 0.91785986, -0.5769914 ],
       [-0.07549497,  0.06432609],
       [-1.16818528, -1.56811842],
       [ 0.123176  ,  0.21008006],
       [-0.57217238,  1.90082616],
       [-0.27416593,  0.21008006],
       [-0.27416593, -1.45151524],
       [-0.07549497, -0.48953901],
       [-0.27416593,  0.26838165],
       [ 1.21586631, -0.98510253],
       [-0.17483045,  2.16318331],
       [-0.07549497,  0.03517529],
       [ 2.20922114,  0.93884993],
       [-0.37350142,  1.31781026],
       [ 2.01055017,  2.16318331],
       [ 1.61320824,  0.0060245 ],
       [-0.27416593,  0.5307388 ],
       [ 1.01719535,  0.76394516],
       [ 0.22251148, -0.13972948],
       [-1.0688498 ,  0.5307388 ],
       [ 0.123176  ,  1.87167537],
       [ 0.91785986, -0.78104696],
       [ 1.11653083,  0.5307388 ],
       [-0.17483045,  1.60931821],
       [-0.27416593, -0.31463425],
       [ 0.42118245,  2.30893729],
       [ 1.31520179,  1.87167537],
       [ 0.32184696,  0.50158801],
       [-0.17483045, -0.5769914 ],
       [-1.26752076, -1.07255491],
       [ 0.7191889 ,  1.78422298],
       [-0.17483045,  1.40526265],
       [ 0.81852438, -1.21830888],
       [ 0.22251148, -0.37293583],
       [-0.07549497, -0.22718186],
       [-0.77084335,  1.08460391],
       [ 0.02384052,  1.25950867],
       [ 2.10988566,  2.13403252],
       [-0.07549497,  0.15177847],
       [ 1.51387276,  0.35583404],
       [-1.16818528, -1.59726922],
       [-0.96951431,  0.41413563],
       [ 1.01719535, -1.07255491],
       [-0.96951431,  0.5598896 ],
       [-0.96951431, -0.31463425],
       [ 0.91785986, -1.30576127],
       [ 0.22251148,  0.03517529],
       [-1.46619173,  0.35583404],
       [ 1.91121469,  0.12262768],
       [-0.27416593,  0.15177847],
       [-0.96951431,  1.55101662],
       [-0.57217238,  1.37611185],
       [-1.46619173, -0.11057868],
       [ 0.22251148, -0.66444378],
       [-0.07549497, -0.43123742],
       [-1.0688498 ,  0.76394516],
       [ 0.22251148,  0.23923086],
       [ 2.01055017,  0.73479437],
       [-0.77084335, -0.22718186],
       [-1.86353366, -1.27661047],
       [-0.27416593, -0.5769914 ],
       [-1.0688498 , -1.53896763],
       [-0.27416593, -1.36406286],
       [-1.36685625, -1.48066604],
       [-0.87017883, -0.66444378],
       [ 0.7191889 , -1.10170571],
       [ 1.91121469, -0.28548345],
       [ 0.32184696, -0.72274537],
       [-0.4728369 , -0.83934855],
       [ 1.11653083, -1.21830888],
       [-0.27416593, -1.24745968],
       [-0.27416593,  0.06432609],
       [ 2.20922114, -0.69359458],
       [ 1.51387276, -1.04340412],
       [ 0.91785986, -0.5478406 ],
       [ 0.42118245, -0.13972948],
       [-1.46619173, -0.63529299],
       [-0.67150786, -0.34378504],
       [-0.27416593, -0.89765014],
       [-0.77084335,  1.90082616],
       [ 2.01055017, -1.36406286],
       [-0.07549497,  0.29753245],
       [ 1.11653083, -1.21830888],
       [-1.36685625,  0.41413563],
       [ 0.02384052, -0.43123742],
       [ 1.01719535, -1.01425332],
       [-0.27416593, -0.66444378],
       [-1.96286914,  0.35583404],
       [-0.57217238, -1.50981683],
       [-0.27416593, -0.28548345],
       [ 1.01719535,  1.87167537],
       [ 0.32184696,  0.06432609],
       [ 0.02384052, -0.25633266],
       [ 0.91785986, -0.60614219],
       [-0.07549497, -0.37293583],
       [ 2.10988566,  0.38498483],
       [-0.87017883, -0.78104696],
       [-0.77084335,  0.5598896 ],
       [ 1.01719535,  2.07573093],
       [ 0.02384052,  1.23035788],
       [ 2.10988566,  1.75507219],
       [ 1.81187921,  1.84252457],
       [-1.86353366,  0.0060245 ],
       [ 2.20922114,  0.38498483],
       [-0.27416593, -0.5769914 ],
       [-0.07549497,  0.21008006],
       [-0.4728369 , -0.0231263 ],
       [ 0.81852438,  0.5307388 ],
       [-0.17483045, -0.51868981],
       [ 0.02384052,  0.29753245],
       [-0.07549497,  0.67649278],
       [ 0.7191889 , -0.72274537],
       [ 1.01719535,  1.43441344],
       [-0.96951431, -0.43123742],
       [-0.4728369 , -0.5478406 ],
       [-1.0688498 , -1.1308565 ],
       [-1.76419818,  0.47243721],
       [-0.07549497, -1.07255491],
       [ 0.123176  ,  1.05545311],
       [-1.0688498 ,  1.95912775],
       [-1.56552721, -1.50981683],
       [-0.27416593, -1.39321365],
       [-0.67150786, -1.50981683],
       [ 1.51387276,  2.13403252],
       [-0.4728369 , -0.28548345],
       [ 0.91785986,  1.25950867],
       [ 0.81852438,  0.35583404],
       [-0.27416593, -0.25633266],
       [-1.86353366,  0.44328642],
       [ 0.81852438, -0.83934855],
       [-0.27416593,  2.2506357 ],
       [-0.87017883,  0.38498483],
       [ 1.31520179,  2.2214849 ],
       [ 0.32184696, -0.31463425],
       [-0.57217238,  1.37611185],
       [ 0.123176  ,  1.87167537],
       [ 0.81852438,  0.26838165],
       [-0.77084335, -0.60614219],
       [ 1.61320824,  1.1137547 ],
       [-1.76419818, -0.60614219],
       [-1.0688498 ,  0.58904039],
       [-1.56552721,  0.32668324],
       [ 2.20922114, -0.81019776],
       [ 0.32184696,  0.06432609],
       [ 0.81852438,  0.76394516],
       [ 0.42118245, -0.46038822],
       [ 0.32184696, -0.19803107],
       [ 0.81852438, -1.39321365],
       [ 0.02384052, -0.31463425],
       [ 0.81852438,  0.12262768],
       [-0.27416593, -0.48953901],
       [-1.96286914, -0.75189617],
       [ 1.61320824, -1.27661047],
       [ 1.01719535, -1.18915809],
       [ 0.91785986, -0.66444378],
       [ 1.51387276,  0.99715152],
       [ 0.32184696, -0.5478406 ],
       [ 0.123176  ,  1.52186583],
       [-0.77084335, -1.59726922],
       [-1.0688498 ,  0.5598896 ],
       [ 0.42118245,  0.29753245],
       [ 0.123176  ,  0.09347688],
       [-0.4728369 , -0.78104696],
       [-0.67150786,  1.40526265],
       [ 0.32184696, -1.16000729],
       [-1.46619173, -0.19803107],
       [-0.17483045,  0.85139755],
       [-1.96286914,  0.47243721],
       [ 0.32184696, -0.28548345],
       [ 1.01719535,  1.78422298],
       [-0.87017883, -1.21830888],
       [-1.46619173, -1.21830888],
       [ 1.41453728, -1.42236445],
       [-1.36685625, -1.24745968],
       [-1.16818528, -0.78104696],
       [-1.26752076,  0.29753245],
       [-0.27416593,  0.03517529],
       [-1.16818528, -1.10170571],
       [-0.37350142,  1.23035788],
       [ 0.7191889 , -1.39321365],
       [ 0.42118245,  0.29753245],
       [-0.96951431,  0.50158801],
       [ 1.21586631, -0.75189617],
       [ 0.123176  ,  0.03517529],
       [-0.57217238,  2.33808808],
       [-1.16818528, -1.01425332],
       [ 1.91121469,  1.52186583],
       [ 1.01719535, -1.16000729],
       [-0.67150786, -1.59726922],
       [ 1.11653083,  0.12262768],
       [-0.27416593, -0.13972948],
       [ 0.42118245,  1.1137547 ],
       [ 0.02384052,  0.03517529],
       [-0.96951431,  0.44328642],
       [ 1.91121469, -1.27661047],
       [ 0.91785986,  1.02630232],
       [ 1.41453728,  2.33808808],
       [ 0.02384052,  0.03517529],
       [-1.0688498 , -1.45151524],
       [-1.36685625, -0.43123742],
       [ 0.123176  , -0.81019776],
       [-0.07549497, -0.51868981],
       [-1.0688498 , -0.34378504],
       [-1.16818528,  0.32668324],
       [ 0.123176  ,  0.76394516],
       [-1.16818528, -1.59726922],
       [ 0.123176  ,  0.15177847],
       [-0.37350142, -1.30576127],
       [ 0.32184696, -0.51868981],
       [-0.57217238,  0.88054834],
       [-1.16818528,  0.29753245],
       [ 0.42118245,  0.0060245 ],
       [-1.66486269,  0.06432609],
       [ 1.61320824,  0.99715152],
       [ 1.21586631,  0.5307388 ],
       [-1.76419818,  0.35583404],
       [ 0.32184696,  0.06432609],
       [ 0.32184696,  0.26838165],
       [ 0.91785986, -1.16000729],
       [-0.4728369 ,  2.30893729],
       [ 1.41453728, -0.92680094],
       [-0.27416593,  0.09347688],
       [ 2.20922114, -1.04340412],
       [ 1.31520179, -1.36406286],
       [ 1.11653083,  0.47243721],
       [-0.67150786,  0.18092927],
       [ 0.32184696,  0.06432609],
       [-1.0688498 , -0.34378504],
       [ 0.42118245,  0.26838165],
       [-0.17483045, -0.28548345],
       [-0.07549497,  2.2214849 ],
       [ 0.32184696,  0.03517529],
       [-1.56552721, -1.24745968],
       [-0.67150786,  0.5598896 ],
       [-1.76419818,  0.35583404],
       [ 0.22251148,  1.08460391],
       [-1.16818528, -0.51868981],
       [-0.27416593,  1.1137547 ],
       [ 0.42118245,  0.99715152],
       [-1.0688498 ,  0.41413563],
       [ 1.41453728,  1.28865947],
       [-0.96951431, -1.10170571],
       [-0.67150786, -0.11057868],
       [-1.36685625, -0.43123742],
       [ 1.01719535,  1.98827854],
       [-0.4728369 , -1.21830888],
       [ 0.52051793,  1.84252457],
       [ 0.02384052, -0.5769914 ],
       [-1.16818528, -1.16000729],
       [ 0.42118245, -0.13972948],
       [ 0.123176  ,  0.03517529],
       [-0.77084335,  0.26838165],
       [ 0.7191889 , -1.27661047],
       [ 0.91785986,  2.16318331],
       [ 0.81852438, -1.36406286],
       [-0.17483045, -1.07255491],
       [-0.67150786,  0.03517529],
       [ 1.01719535,  0.58904039],
       [-0.07549497,  1.95912775],
       [ 2.20922114,  1.1137547 ],
       [-0.07549497,  0.29753245],
       [-0.96951431,  0.26838165],
       [ 0.02384052, -0.5769914 ],
       [-1.36685625, -0.34378504],
       [-0.87017883,  0.29753245],
       [-0.17483045,  0.15177847],
       [ 0.42118245, -0.48953901],
       [-1.56552721, -0.19803107],
       [-0.27416593, -0.92680094],
       [-0.27416593, -0.34378504],
       [-0.27416593, -0.75189617],
       [-1.66486269, -1.56811842],
       [ 0.42118245, -0.16888027],
       [-0.4728369 , -1.1308565 ]])

In [20]:
x_test

array([[ 1.41453728,  0.58904039],
       [ 1.51387276,  0.06432609],
       [ 0.22251148,  0.06432609],
       [ 1.91121469, -1.07255491],
       [ 0.22251148, -0.25633266],
       [-1.86353366, -1.42236445],
       [-0.57217238,  0.47243721],
       [-0.27416593,  0.06432609],
       [-1.26752076,  0.50158801],
       [ 2.10988566, -1.18915809],
       [-0.87017883,  0.15177847],
       [ 0.7191889 ,  0.26838165],
       [-1.36685625, -1.10170571],
       [ 1.81187921, -0.28548345],
       [ 0.123176  , -0.81019776],
       [-1.86353366,  0.18092927],
       [-1.16818528,  0.06432609],
       [ 0.91785986, -1.45151524],
       [-1.96286914, -0.51868981],
       [-1.76419818, -1.36406286],
       [-0.07549497,  0.26838165],
       [ 1.71254373,  1.60931821],
       [-0.27416593, -0.43123742],
       [ 0.22251148,  0.15177847],
       [-0.87017883, -0.25633266],
       [-1.96286914, -0.05227709],
       [-0.87017883,  2.27978649],
       [-1.26752076,  0.58904039],
       [ 0.91785986, -1.36406286],
       [ 0.02384052, -0.25633266],
       [ 0.52051793,  1.23035788],
       [ 0.22251148, -0.37293583],
       [ 2.10988566, -0.81019776],
       [-1.16818528,  1.40526265],
       [-0.27416593,  0.15177847],
       [ 0.7191889 , -1.39321365],
       [-1.16818528,  0.29753245],
       [-0.27416593,  0.79309596],
       [-1.76419818, -0.98510253],
       [ 2.20922114, -0.81019776],
       [-1.36685625, -1.36406286],
       [ 0.81852438,  1.37611185],
       [ 0.52051793,  1.72592139],
       [ 1.11653083,  2.07573093],
       [-0.87017883,  0.38498483],
       [-0.07549497,  2.16318331],
       [ 2.01055017, -0.66444378],
       [ 2.10988566,  0.5307388 ],
       [-0.67150786, -0.05227709],
       [ 0.02384052, -0.5478406 ],
       [ 0.81852438, -0.31463425],
       [-0.77084335,  0.50158801],
       [ 0.91785986, -1.04340412],
       [ 1.01719535,  0.12262768],
       [ 0.22251148,  0.15177847],
       [ 0.32184696,  0.29753245],
       [ 0.42118245,  0.09347688],
       [-0.27416593, -1.30576127],
       [-0.57217238,  1.46356424],
       [ 0.61985341,  2.01742934],
       [-1.66486269,  0.5307388 ],
       [-0.37350142, -0.78104696],
       [ 1.11653083, -0.89765014],
       [-1.0688498 , -0.37293583],
       [-0.96951431, -0.95595173],
       [ 1.11653083,  0.5598896 ],
       [-0.96951431, -0.75189617],
       [-0.77084335, -1.53896763],
       [-1.56552721, -0.43123742],
       [ 1.81187921,  0.99715152],
       [-1.46619173, -1.45151524],
       [ 0.22251148, -0.37293583],
       [-1.36685625,  0.5598896 ],
       [ 0.02384052, -0.13972948],
       [ 0.22251148,  2.10488172],
       [ 1.41453728,  1.98827854],
       [-0.4728369 ,  1.25950867],
       [-1.16818528, -1.53896763],
       [ 1.01719535, -1.07255491],
       [ 2.01055017,  0.90969914],
       [-1.66486269, -0.05227709],
       [-0.17483045,  1.63846901],
       [ 0.61985341, -0.89765014],
       [-1.26752076, -1.39321365],
       [-1.76419818,  0.12262768],
       [-0.37350142,  0.06432609],
       [ 0.123176  , -0.31463425],
       [ 1.71254373, -0.89765014],
       [ 0.123176  , -0.25633266],
       [-0.07549497,  0.0060245 ],
       [ 0.42118245,  0.58904039],
       [-1.86353366, -1.30576127],
       [ 0.91785986,  1.08460391],
       [ 0.123176  ,  0.26838165],
       [-0.27416593, -0.37293583],
       [-1.26752076,  0.26838165],
       [ 2.01055017, -0.92680094],
       [-0.77084335,  1.34696106],
       [ 0.22251148, -0.31463425],
       [-1.0688498 , -0.46038822]])

In [21]:
from sklearn import tree
#clf = tree.DecisionTreeClassifier(criterion='entropy', random_state=0)
clf = tree.DecisionTreeClassifier(criterion='gini')

In [22]:
clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [23]:
y_pred = clf.predict(x_test)

In [24]:
from sklearn.metrics import confusion_matrix

In [25]:
confusion_matrix(y_test, y_pred)

array([[54,  8],
       [12, 26]])

In [26]:
y_pred1 = clf.predict(x_test)

In [27]:
(43+21)/(43+21+11+5)

0.8

In [28]:
confusion_matrix(y_test, y_pred)

array([[54,  8],
       [12, 26]])

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
from sklearn.metrics import classification_report

In [31]:
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.82      0.87      0.84        62
           1       0.76      0.68      0.72        38

    accuracy                           0.80       100
   macro avg       0.79      0.78      0.78       100
weighted avg       0.80      0.80      0.80       100

In [32]:
new_ind = np.array([[29, 95000]])
new_ind_sc = sc_x.transform(new_ind)
pred = clf.predict(new_ind_sc)

In [33]:
pred

array([1])

In [35]:
# 31 oct
## Naive bayes classifier
# code for decision tree classifier
from sklearn import tree
#clf = tree.DecisionTreeClassifier(criterion='entropy', random_state=0)
clf = tree.DecisionTreeClassifier(criterion='gini')
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [36]:
cm = confusion_matrix(y_test, y_pred1)
cm

array([[54,  8],
       [12, 26]])

In [38]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred1)*100)

Accuracy: 80.0

In [39]:
# KNN classifier
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
# minkwski is p=2, manhattan is p=1, euclidean is p=2

In [40]:
y_preds = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_preds)
cm
accuracy = metrics.accuracy_score(y_test, y_preds)
print("Accuracy:", accuracy*100)

Accuracy: 89.0

In [43]:
# euclidean distance knn implementation
import math
from collections import Counter

def euclidean_distance(point1, point2):
    return math.sqrt(sum((a - b) ** 2 for a, b in zip(point1, point2)))

def knn(train_data, train_labels, test_point, k):
    distances = []

    # step 1: compute the distance between the test point and all training points
    for i in range(len(train_data)):
        dist = euclidean_distance(train_data[i], test_point)
        distances.append((dist, train_labels[i]))

    # step 2: sort by distance
    distances.sort(key=lambda x: x[0])

    #step 3: select k nearest neighbors
    k_nearest_neighbors = distances[:k]

    # extract labels
    labels = [label for _, label in k_nearest_neighbors]

    #step 4: majority vote
    return Counter(labels).most_common(1)[0][0]

In [44]:
x_train = [(2,4),(4,4),(4,6),(6,8)]
y_train = ["Red", "Red", "Blue", "Blue"]

test_point = (5, 5)
k=3

print("Predicted class for test point", test_point, "is", knn(x_train, y_train, test_point, k))

Predicted class for test point (5, 5) is Red

In [ ]:
# ensemble methods boosting adaboost
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import LabelEncoder

In [47]:
data = pd.read_csv(r"D:\msis-labs\msis-labs\aml-lab\projects\data\mushrooms.csv")

In [48]:
data.head(5)

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [49]:
y = data['class']
x = data.iloc[:, 1:]

# encode the labels
le = LabelEncoder()
y = le.fit_transform(y)

In [50]:
# label encoding for categorical features in x
le_x = LabelEncoder()
for label in x.columns:
    x[label] = le_x.fit_transform(x[label])

In [53]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=45)

In [57]:
from sklearn.tree import DecisionTreeClassifier
model1 = DecisionTreeClassifier(criterion='entropy', max_depth=1, random_state=42)
model2 = AdaBoostClassifier(estimator = model1, n_estimators=150, learning_rate=0.1, random_state=42)
boostmodel = model2.fit(x_train, y_train)

In [58]:
y_preds = boostmodel.predict(x_test)
cm = confusion_matrix(y_test, y_preds)
cm

array([[1252,    3],
       [ 100, 1083]])

In [59]:
acc = metrics.accuracy_score(y_test, y_preds)
print("Accuracy:", acc*100)

Accuracy: 95.77522559474978

In [61]:
# random forest classifier
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=150, criterion='entropy', random_state=42)
classifier.fit(x_train, y_train)
y_preds = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_preds)
cm
acc = metrics.accuracy_score(y_test, y_preds)
print("Accuracy:", acc*100)

Accuracy: 100.0

In [64]:
# Logistic regression
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(random_state=42, max_iter=100)
logistic_model.fit(x_train, y_train)
y_preds = logistic_model.predict(x_test)
cm = confusion_matrix(y_test, y_preds)
cm
acc = metrics.accuracy_score(y_test, y_preds)
print("Accuracy:", acc*100)

Accuracy: 94.70877768662838

C:\Users\HP\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [65]:
l2_logistic = LogisticRegression(penalty='l2', C=1.0, random_state=42, max_iter=100)
l2_logistic.fit(x_train, y_train)
y_preds = l2_logistic.predict(x_test)
cm = confusion_matrix(y_test, y_preds)
cm
acc = metrics.accuracy_score(y_test, y_preds)
print("Accuracy:", acc*100)

Accuracy: 94.70877768662838

C:\Users\HP\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [66]:
l2_logistic = LogisticRegression(penalty='l1', solver='liblinear', C=1.0, random_state=42, max_iter=100)
l2_logistic.fit(x_train, y_train)
y_preds = l2_logistic.predict(x_test)
cm = confusion_matrix(y_test, y_preds)
cm
acc = metrics.accuracy_score(y_test, y_preds)
print("Accuracy:", acc*100)

C:\Users\HP\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

Accuracy: 95.61115668580804

In [67]:
# multi class logistic regression

multiclass_logistic = LogisticRegression(solver='lbfgs', random_state=42, max_iter=1000)
multiclass_logistic.fit(x_train, y_train)
y_preds = multiclass_logistic.predict(x_test)
cm = confusion_matrix(y_test, y_preds)
cm
acc = metrics.accuracy_score(y_test, y_preds)
print("Accuracy:", acc*100)

Accuracy: 94.74979491386382

In [73]:
# pca

data = pd.read_csv(r"D:\Downloads\Wine.csv")
dataset = data

x = dataset.iloc[:, 0:13].values
y = dataset.iloc[:, 13].values
y.shape

(178,)

In [74]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.337343  , 0.16894025])

In [79]:
classifier = LogisticRegression(random_state=42, max_iter=100)
classifier.fit(x_train, y_train)
y_preds = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_preds)
print(cm)
acc = metrics.accuracy_score(y_test, y_preds)
print("Accuracy:", acc*100)

[[937 318]
 [342 841]]
Accuracy: 72.92863002461034

In [82]:
dataset['Customer_Segment'].unique()

array([1, 2, 3])