Social Network Ads Dataset Decision Tree

In [2]:
print("Hello world")

Hello world

In [5]:
import pandas as pd

In [ ]:
# Age is in a differen scale than estimated salary. Thus we need to convert them into a standard scale.

In [6]:
df = pd.read_csv("/home/msis/ahegde/aml-lab/projects/data/Social_Network_Ads.csv")

In [7]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [8]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [9]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [13]:
x = df.iloc[:, 2:4].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],
       [    27,  58000],
       [    24,  55000],
       [    23,  48000],
       [    28,  79000],
       [    22,  18000],
       [    32, 117000],
       [    27,  20000],
       [    25,  87000],
       [    23,  66000],
       [    32, 120000],
       [    59,  83000],
       [    24,  58000],
       [    24,  19000],
       [    23,  82000],
       [    22,  63000],
       [    31,  68000],
       [    25,  80000],
       [    24,  27000],
       [    20,  23000],
       [    33, 113000],
       [    32,  18000],
       [    34, 112000],
       [    18,  52000],
       [    22,  27000],
       [    28,  87000],
       [    26,  17000],
       [    30,  80000],
       [    39,  42000],
       [    20,  49000],
       [    35,  88000],
       [    30,  62000],
       [    31, 118000],
       [    24,  55000],
       [    28,  85000],
       [    26,  81000],
       [    35,  50000],
       [    22,  81000],
       [    30, 116000],
       [    26,  15000],
       [    29,  28000],
       [    29,  83000],
       [    35,  44000],
       [    35,  25000],
       [    28, 123000],
       [    35,  73000],
       [    28,  37000],
       [    27,  88000],
       [    28,  59000],
       [    32,  86000],
       [    33, 149000],
       [    19,  21000],
       [    21,  72000],
       [    26,  35000],
       [    27,  89000],
       [    26,  86000],
       [    38,  80000],
       [    39,  71000],
       [    37,  71000],
       [    38,  61000],
       [    37,  55000],
       [    42,  80000],
       [    40,  57000],
       [    35,  75000],
       [    36,  52000],
       [    40,  59000],
       [    41,  59000],
       [    36,  75000],
       [    37,  72000],
       [    40,  75000],
       [    35,  53000],
       [    41,  51000],
       [    39,  61000],
       [    42,  65000],
       [    26,  32000],
       [    30,  17000],
       [    26,  84000],
       [    31,  58000],
       [    33,  31000],
       [    30,  87000],
       [    21,  68000],
       [    28,  55000],
       [    23,  63000],
       [    20,  82000],
       [    30, 107000],
       [    28,  59000],
       [    19,  25000],
       [    19,  85000],
       [    18,  68000],
       [    35,  59000],
       [    30,  89000],
       [    34,  25000],
       [    24,  89000],
       [    27,  96000],
       [    41,  30000],
       [    29,  61000],
       [    20,  74000],
       [    26,  15000],
       [    41,  45000],
       [    31,  76000],
       [    36,  50000],
       [    40,  47000],
       [    31,  15000],
       [    46,  59000],
       [    29,  75000],
       [    26,  30000],
       [    32, 135000],
       [    32, 100000],
       [    25,  90000],
       [    37,  33000],
       [    35,  38000],
       [    33,  69000],
       [    18,  86000],
       [    22,  55000],
       [    35,  71000],
       [    29, 148000],
       [    29,  47000],
       [    21,  88000],
       [    34, 115000],
       [    26, 118000],
       [    34,  43000],
       [    34,  72000],
       [    23,  28000],
       [    35,  47000],
       [    25,  22000],
       [    24,  23000],
       [    31,  34000],
       [    26,  16000],
       [    31,  71000],
       [    32, 117000],
       [    33,  43000],
       [    33,  60000],
       [    31,  66000],
       [    20,  82000],
       [    33,  41000],
       [    35,  72000],
       [    28,  32000],
       [    24,  84000],
       [    19,  26000],
       [    29,  43000],
       [    19,  70000],
       [    28,  89000],
       [    34,  43000],
       [    30,  79000],
       [    20,  36000],
       [    26,  80000],
       [    35,  22000],
       [    35,  39000],
       [    49,  74000],
       [    39, 134000],
       [    41,  71000],
       [    58, 101000],
       [    47,  47000],
       [    55, 130000],
       [    52, 114000],
       [    40, 142000],
       [    46,  22000],
       [    48,  96000],
       [    52, 150000],
       [    59,  42000],
       [    35,  58000],
       [    47,  43000],
       [    60, 108000],
       [    49,  65000],
       [    40,  78000],
       [    46,  96000],
       [    59, 143000],
       [    41,  80000],
       [    35,  91000],
       [    37, 144000],
       [    60, 102000],
       [    35,  60000],
       [    37,  53000],
       [    36, 126000],
       [    56, 133000],
       [    40,  72000],
       [    42,  80000],
       [    35, 147000],
       [    39,  42000],
       [    40, 107000],
       [    49,  86000],
       [    38, 112000],
       [    46,  79000],
       [    40,  57000],
       [    37,  80000],
       [    46,  82000],
       [    53, 143000],
       [    42, 149000],
       [    38,  59000],
       [    50,  88000],
       [    56, 104000],
       [    41,  72000],
       [    51, 146000],
       [    35,  50000],
       [    57, 122000],
       [    41,  52000],
       [    35,  97000],
       [    44,  39000],
       [    37,  52000],
       [    48, 134000],
       [    37, 146000],
       [    50,  44000],
       [    52,  90000],
       [    41,  72000],
       [    40,  57000],
       [    58,  95000],
       [    45, 131000],
       [    35,  77000],
       [    36, 144000],
       [    55, 125000],
       [    35,  72000],
       [    48,  90000],
       [    42, 108000],
       [    40,  75000],
       [    37,  74000],
       [    47, 144000],
       [    40,  61000],
       [    43, 133000],
       [    59,  76000],
       [    60,  42000],
       [    39, 106000],
       [    57,  26000],
       [    57,  74000],
       [    38,  71000],
       [    49,  88000],
       [    52,  38000],
       [    50,  36000],
       [    59,  88000],
       [    35,  61000],
       [    37,  70000],
       [    52,  21000],
       [    48, 141000],
       [    37,  93000],
       [    37,  62000],
       [    48, 138000],
       [    41,  79000],
       [    37,  78000],
       [    39, 134000],
       [    49,  89000],
       [    55,  39000],
       [    37,  77000],
       [    35,  57000],
       [    36,  63000],
       [    42,  73000],
       [    43, 112000],
       [    45,  79000],
       [    46, 117000],
       [    58,  38000],
       [    48,  74000],
       [    37, 137000],
       [    37,  79000],
       [    40,  60000],
       [    42,  54000],
       [    51, 134000],
       [    47, 113000],
       [    36, 125000],
       [    38,  50000],
       [    42,  70000],
       [    39,  96000],
       [    38,  50000],
       [    49, 141000],
       [    39,  79000],
       [    39,  75000],
       [    54, 104000],
       [    35,  55000],
       [    45,  32000],
       [    36,  60000],
       [    52, 138000],
       [    53,  82000],
       [    41,  52000],
       [    48,  30000],
       [    48, 131000],
       [    41,  60000],
       [    41,  72000],
       [    42,  75000],
       [    36, 118000],
       [    47, 107000],
       [    38,  51000],
       [    48, 119000],
       [    42,  65000],
       [    40,  65000],
       [    57,  60000],
       [    36,  54000],
       [    58, 144000],
       [    35,  79000],
       [    38,  55000],
       [    39, 122000],
       [    53, 104000],
       [    35,  75000],
       [    38,  65000],
       [    47,  51000],
       [    47, 105000],
       [    41,  63000],
       [    53,  72000],
       [    54, 108000],
       [    39,  77000],
       [    38,  61000],
       [    38, 113000],
       [    37,  75000],
       [    42,  90000],
       [    37,  57000],
       [    36,  99000],
       [    60,  34000],
       [    54,  70000],
       [    41,  72000],
       [    40,  71000],
       [    42,  54000],
       [    43, 129000],
       [    53,  34000],
       [    47,  50000],
       [    42,  79000],
       [    42, 104000],
       [    59,  29000],
       [    58,  47000],
       [    46,  88000],
       [    38,  71000],
       [    54,  26000],
       [    60,  46000],
       [    60,  83000],
       [    39,  73000],
       [    59, 130000],
       [    37,  80000],
       [    46,  32000],
       [    46,  74000],
       [    42,  53000],
       [    41,  87000],
       [    58,  23000],
       [    42,  64000],
       [    48,  33000],
       [    44, 139000],
       [    49,  28000],
       [    57,  33000],
       [    56,  60000],
       [    49,  39000],
       [    39,  71000],
       [    47,  34000],
       [    48,  35000],
       [    48,  33000],
       [    47,  23000],
       [    45,  45000],
       [    60,  42000],
       [    39,  59000],
       [    46,  41000],
       [    51,  23000],
       [    50,  20000],
       [    36,  33000],
       [    49,  36000]])

In [15]:
y = df.iloc[:, -1].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1])

In [16]:
import numpy as np

In [50]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=45)

In [19]:
x_test.astype(int)

array([[    52,  90000],
       [    53,  72000],
       [    40,  72000],
       [    57,  33000],
       [    40,  61000],
       [    19,  21000],
       [    32,  86000],
       [    35,  72000],
       [    25,  87000],
       [    59,  29000],
       [    29,  75000],
       [    45,  79000],
       [    24,  32000],
       [    56,  60000],
       [    39,  42000],
       [    19,  76000],
       [    26,  72000],
       [    47,  20000],
       [    18,  52000],
       [    20,  23000],
       [    37,  79000],
       [    55, 125000],
       [    35,  55000],
       [    40,  75000],
       [    29,  61000],
       [    18,  68000],
       [    29, 148000],
       [    25,  90000],
       [    47,  23000],
       [    38,  61000],
       [    43, 112000],
       [    40,  57000],
       [    59,  42000],
       [    26, 118000],
       [    35,  75000],
       [    45,  22000],
       [    26,  80000],
       [    35,  97000],
       [    20,  36000],
       [    60,  42000],
       [    24,  23000],
       [    46, 117000],
       [    43, 129000],
       [    49, 141000],
       [    29,  83000],
       [    37, 144000],
       [    58,  47000],
       [    59,  88000],
       [    31,  68000],
       [    38,  51000],
       [    46,  59000],
       [    30,  87000],
       [    47,  34000],
       [    48,  74000],
       [    40,  75000],
       [    41,  80000],
       [    42,  73000],
       [    35,  25000],
       [    32, 120000],
       [    44, 139000],
       [    21,  88000],
       [    34,  43000],
       [    49,  39000],
       [    27,  57000],
       [    28,  37000],
       [    49,  89000],
       [    28,  44000],
       [    30,  17000],
       [    22,  55000],
       [    56, 104000],
       [    23,  20000],
       [    40,  57000],
       [    24,  89000],
       [    38,  65000],
       [    40, 142000],
       [    52, 138000],
       [    33, 113000],
       [    26,  17000],
       [    48,  33000],
       [    58, 101000]])

In [25]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [30]:
x_train

array([[-1.64383039, -0.04716677],
       [-0.16067515,  1.66262849],
       [ 0.63034098, -0.90206439],
       [-1.24832233, -1.40321127],
       [-1.74270741,  0.12970861],
       [-0.35842918,  0.07075015],
       [ 0.1359559 , -0.31247982],
       [ 1.71798816, -0.90206439],
       [ 0.1359559 , -0.25352136],
       [-0.06179814,  0.01179169],
       [ 0.43258695,  0.60137626],
       [-1.84158443, -1.31477359],
       [ 0.92697203,  1.10252314],
       [ 0.1359559 ,  0.27710475],
       [-0.25955217, -0.37143828],
       [-1.24832233,  0.27710475],
       [ 2.0146192 , -0.93154362],
       [-0.75393725,  1.3678362 ],
       [ 0.23483291, -0.31247982],
       [-1.0505683 , -0.45987596],
       [ 0.43258695,  0.15918783],
       [-1.84158443, -1.49164896],
       [ 0.82809501, -1.10841899],
       [-0.16067515, -0.45987596],
       [-0.25955217,  0.63085549],
       [ 1.71798816,  1.7805454 ],
       [-0.65506023,  0.12970861],
       [ 0.23483291, -0.28300059],
       [ 1.02584904, -0.84310593],
       [-0.06179814,  0.24762552],
       [ 0.43258695, -0.45987596],
       [ 0.33370993, -0.51883442],
       [-0.06179814,  0.12970861],
       [-0.65506023, -1.04946053],
       [-1.14944531,  0.42450089],
       [ 1.12472606, -0.99050208],
       [ 1.12472606, -0.13560445],
       [ 1.22360307, -1.46216973],
       [ 2.11349622,  0.18866706],
       [-0.75393725,  0.30658398],
       [-1.14944531,  0.48345935],
       [-0.95169128, -0.31247982],
       [-0.16067515, -0.19456291],
       [-0.85281426, -0.78414748],
       [-0.55618322, -1.52112819],
       [-0.35842918, -0.78414748],
       [ 0.92697203, -0.57779288],
       [-0.06179814,  0.07075015],
       [-1.14944531, -1.58008665],
       [ 0.1359559 ,  0.21814629],
       [-0.55618322,  1.92794154],
       [-0.25955217,  0.21814629],
       [-0.25955217, -1.46216973],
       [-0.06179814, -0.48935519],
       [-0.25955217,  0.27710475],
       [ 1.22360307, -0.99050208],
       [-0.16067515,  2.1932546 ],
       [-0.06179814,  0.04127092],
       [ 2.21237324,  0.955127  ],
       [-0.35842918,  1.33835697],
       [ 2.0146192 ,  2.1932546 ],
       [ 1.61911114,  0.01179169],
       [-0.25955217,  0.5424178 ],
       [ 1.02584904,  0.77825163],
       [ 0.23483291, -0.13560445],
       [-1.0505683 ,  0.5424178 ],
       [ 0.1359559 ,  1.89846231],
       [ 0.92697203, -0.78414748],
       [ 1.12472606,  0.5424178 ],
       [-0.16067515,  1.63314926],
       [-0.25955217, -0.31247982],
       [ 0.43258695,  2.34065074],
       [ 1.32248009,  1.89846231],
       [ 0.33370993,  0.51293858],
       [-0.16067515, -0.57779288],
       [-1.24832233, -1.07893976],
       [ 0.72921799,  1.81002463],
       [-0.16067515,  1.42679466],
       [ 0.82809501, -1.2263359 ],
       [ 0.23483291, -0.37143828],
       [-0.06179814, -0.22404214],
       [-0.75393725,  1.10252314],
       [ 0.03707888,  1.27939852],
       [ 2.11349622,  2.16377537],
       [-0.06179814,  0.15918783],
       [ 1.52023412,  0.36554243],
       [-1.14944531, -1.60956587],
       [-0.95169128,  0.42450089],
       [ 1.02584904, -1.07893976],
       [-0.95169128,  0.57189703],
       [-0.95169128, -0.31247982],
       [ 0.92697203, -1.31477359],
       [ 0.23483291,  0.04127092],
       [-1.44607636,  0.36554243],
       [ 1.91574219,  0.12970861],
       [-0.25955217,  0.15918783],
       [-0.95169128,  1.5741908 ],
       [-0.55618322,  1.39731543],
       [-1.44607636, -0.10612522],
       [ 0.23483291, -0.66623056],
       [-0.06179814, -0.43039674],
       [-1.0505683 ,  0.77825163],
       [ 0.23483291,  0.24762552],
       [ 2.0146192 ,  0.7487724 ],
       [-0.75393725, -0.22404214],
       [-1.84158443, -1.28529436],
       [-0.25955217, -0.57779288],
       [-1.0505683 , -1.55060742],
       [-0.25955217, -1.37373205],
       [-1.34719935, -1.49164896],
       [-0.85281426, -0.66623056],
       [ 0.72921799, -1.10841899],
       [ 1.91574219, -0.28300059],
       [ 0.33370993, -0.72518902],
       [-0.4573062 , -0.84310593],
       [ 1.12472606, -1.2263359 ],
       [-0.25955217, -1.25581513],
       [-0.25955217,  0.07075015],
       [ 2.21237324, -0.69570979],
       [ 1.52023412, -1.04946053],
       [ 0.92697203, -0.54831365],
       [ 0.43258695, -0.13560445],
       [-1.44607636, -0.63675133],
       [-0.65506023, -0.34195905],
       [-0.25955217, -0.90206439],
       [-0.75393725,  1.92794154],
       [ 2.0146192 , -1.37373205],
       [-0.06179814,  0.30658398],
       [ 1.12472606, -1.2263359 ],
       [-1.34719935,  0.42450089],
       [ 0.03707888, -0.43039674],
       [ 1.02584904, -1.0199813 ],
       [-0.25955217, -0.66623056],
       [-1.94046144,  0.36554243],
       [-0.55618322, -1.52112819],
       [-0.25955217, -0.28300059],
       [ 1.02584904,  1.89846231],
       [ 0.33370993,  0.07075015],
       [ 0.03707888, -0.25352136],
       [ 0.92697203, -0.60727211],
       [-0.06179814, -0.37143828],
       [ 2.11349622,  0.39502166],
       [-0.85281426, -0.78414748],
       [-0.75393725,  0.57189703],
       [ 1.02584904,  2.10481691],
       [ 0.03707888,  1.24991929],
       [ 2.11349622,  1.7805454 ],
       [ 1.81686517,  1.86898308],
       [-1.84158443,  0.01179169],
       [ 2.21237324,  0.39502166],
       [-0.25955217, -0.57779288],
       [-0.06179814,  0.21814629],
       [-0.4573062 , -0.01768754],
       [ 0.82809501,  0.5424178 ],
       [-0.16067515, -0.51883442],
       [ 0.03707888,  0.30658398],
       [-0.06179814,  0.68981395],
       [ 0.72921799, -0.72518902],
       [ 1.02584904,  1.45627389],
       [-0.95169128, -0.43039674],
       [-0.4573062 , -0.54831365],
       [-1.0505683 , -1.13789822],
       [-1.74270741,  0.48345935],
       [-0.06179814, -1.07893976],
       [ 0.1359559 ,  1.07304392],
       [-1.0505683 ,  1.9869    ],
       [-1.54495338, -1.52112819],
       [-0.25955217, -1.40321127],
       [-0.65506023, -1.52112819],
       [ 1.52023412,  2.16377537],
       [-0.4573062 , -0.28300059],
       [ 0.92697203,  1.27939852],
       [ 0.82809501,  0.36554243],
       [-0.25955217, -0.25352136],
       [-1.84158443,  0.45398012],
       [ 0.82809501, -0.84310593],
       [-0.25955217,  2.28169228],
       [-0.85281426,  0.39502166],
       [ 1.32248009,  2.25221305],
       [ 0.33370993, -0.31247982],
       [-0.55618322,  1.39731543],
       [ 0.1359559 ,  1.89846231],
       [ 0.82809501,  0.27710475],
       [-0.75393725, -0.60727211],
       [ 1.61911114,  1.13200237],
       [-1.74270741, -0.60727211],
       [-1.0505683 ,  0.60137626],
       [-1.54495338,  0.3360632 ],
       [ 2.21237324, -0.81362671],
       [ 0.33370993,  0.07075015],
       [ 0.82809501,  0.77825163],
       [ 0.43258695, -0.45987596],
       [ 0.33370993, -0.19456291],
       [ 0.82809501, -1.40321127],
       [ 0.03707888, -0.31247982],
       [ 0.82809501,  0.12970861],
       [-0.25955217, -0.48935519],
       [-1.94046144, -0.75466825],
       [ 1.61911114, -1.28529436],
       [ 1.02584904, -1.19685668],
       [ 0.92697203, -0.66623056],
       [ 1.52023412,  1.01408546],
       [ 0.33370993, -0.54831365],
       [ 0.1359559 ,  1.54471157],
       [-0.75393725, -1.60956587],
       [-1.0505683 ,  0.57189703],
       [ 0.43258695,  0.30658398],
       [ 0.1359559 ,  0.10022938],
       [-0.4573062 , -0.78414748],
       [-0.65506023,  1.42679466],
       [ 0.33370993, -1.16737745],
       [-1.44607636, -0.19456291],
       [-0.16067515,  0.86668932],
       [-1.94046144,  0.48345935],
       [ 0.33370993, -0.28300059],
       [ 1.02584904,  1.81002463],
       [-0.85281426, -1.2263359 ],
       [-1.44607636, -1.2263359 ],
       [ 1.42135711, -1.4326905 ],
       [-1.34719935, -1.25581513],
       [-1.14944531, -0.78414748],
       [-1.24832233,  0.30658398],
       [-0.25955217,  0.04127092],
       [-1.14944531, -1.10841899],
       [-0.35842918,  1.24991929],
       [ 0.72921799, -1.40321127],
       [ 0.43258695,  0.30658398],
       [-0.95169128,  0.51293858],
       [ 1.22360307, -0.75466825],
       [ 0.1359559 ,  0.04127092],
       [-0.55618322,  2.37012997],
       [-1.14944531, -1.0199813 ],
       [ 1.91574219,  1.54471157],
       [ 1.02584904, -1.16737745],
       [-0.65506023, -1.60956587],
       [ 1.12472606,  0.12970861],
       [-0.25955217, -0.13560445],
       [ 0.43258695,  1.13200237],
       [ 0.03707888,  0.04127092],
       [-0.95169128,  0.45398012],
       [ 1.91574219, -1.28529436],
       [ 0.92697203,  1.04356469],
       [ 1.42135711,  2.37012997],
       [ 0.03707888,  0.04127092],
       [-1.0505683 , -1.46216973],
       [-1.34719935, -0.43039674],
       [ 0.1359559 , -0.81362671],
       [-0.06179814, -0.51883442],
       [-1.0505683 , -0.34195905],
       [-1.14944531,  0.3360632 ],
       [ 0.1359559 ,  0.77825163],
       [-1.14944531, -1.60956587],
       [ 0.1359559 ,  0.15918783],
       [-0.35842918, -1.31477359],
       [ 0.33370993, -0.51883442],
       [-0.55618322,  0.89616855],
       [-1.14944531,  0.30658398],
       [ 0.43258695,  0.01179169],
       [-1.64383039,  0.07075015],
       [ 1.61911114,  1.01408546],
       [ 1.22360307,  0.5424178 ],
       [-1.74270741,  0.36554243],
       [ 0.33370993,  0.07075015],
       [ 0.33370993,  0.27710475],
       [ 0.92697203, -1.16737745],
       [-0.4573062 ,  2.34065074],
       [ 1.42135711, -0.93154362],
       [-0.25955217,  0.10022938],
       [ 2.21237324, -1.04946053],
       [ 1.32248009, -1.37373205],
       [ 1.12472606,  0.48345935],
       [-0.65506023,  0.18866706],
       [ 0.33370993,  0.07075015],
       [-1.0505683 , -0.34195905],
       [ 0.43258695,  0.27710475],
       [-0.16067515, -0.28300059],
       [-0.06179814,  2.25221305],
       [ 0.33370993,  0.04127092],
       [-1.54495338, -1.25581513],
       [-0.65506023,  0.57189703],
       [-1.74270741,  0.36554243],
       [ 0.23483291,  1.10252314],
       [-1.14944531, -0.51883442],
       [-0.25955217,  1.13200237],
       [ 0.43258695,  1.01408546],
       [-1.0505683 ,  0.42450089],
       [ 1.42135711,  1.30887774],
       [-0.95169128, -1.10841899],
       [-0.65506023, -0.10612522],
       [-1.34719935, -0.43039674],
       [ 1.02584904,  2.01637923],
       [-0.4573062 , -1.2263359 ],
       [ 0.53146396,  1.86898308],
       [ 0.03707888, -0.57779288],
       [-1.14944531, -1.16737745],
       [ 0.43258695, -0.13560445],
       [ 0.1359559 ,  0.04127092],
       [-0.75393725,  0.27710475],
       [ 0.72921799, -1.28529436],
       [ 0.92697203,  2.1932546 ],
       [ 0.82809501, -1.37373205],
       [-0.16067515, -1.07893976],
       [-0.65506023,  0.04127092],
       [ 1.02584904,  0.60137626],
       [-0.06179814,  1.9869    ],
       [ 2.21237324,  1.13200237],
       [-0.06179814,  0.30658398],
       [-0.95169128,  0.27710475],
       [ 0.03707888, -0.57779288],
       [-1.34719935, -0.34195905],
       [-0.85281426,  0.30658398],
       [-0.16067515,  0.15918783],
       [ 0.43258695, -0.48935519],
       [-1.54495338, -0.19456291],
       [-0.25955217, -0.93154362],
       [-0.25955217, -0.34195905],
       [-0.25955217, -0.75466825],
       [-1.64383039, -1.58008665],
       [ 0.43258695, -0.16508368],
       [-0.4573062 , -1.13789822]])

In [31]:
x_test

array([[ 1.42135711,  0.60137626],
       [ 1.52023412,  0.07075015],
       [ 0.23483291,  0.07075015],
       [ 1.91574219, -1.07893976],
       [ 0.23483291, -0.25352136],
       [-1.84158443, -1.4326905 ],
       [-0.55618322,  0.48345935],
       [-0.25955217,  0.07075015],
       [-1.24832233,  0.51293858],
       [ 2.11349622, -1.19685668],
       [-0.85281426,  0.15918783],
       [ 0.72921799,  0.27710475],
       [-1.34719935, -1.10841899],
       [ 1.81686517, -0.28300059],
       [ 0.1359559 , -0.81362671],
       [-1.84158443,  0.18866706],
       [-1.14944531,  0.07075015],
       [ 0.92697203, -1.46216973],
       [-1.94046144, -0.51883442],
       [-1.74270741, -1.37373205],
       [-0.06179814,  0.27710475],
       [ 1.71798816,  1.63314926],
       [-0.25955217, -0.43039674],
       [ 0.23483291,  0.15918783],
       [-0.85281426, -0.25352136],
       [-1.94046144, -0.04716677],
       [-0.85281426,  2.31117151],
       [-1.24832233,  0.60137626],
       [ 0.92697203, -1.37373205],
       [ 0.03707888, -0.25352136],
       [ 0.53146396,  1.24991929],
       [ 0.23483291, -0.37143828],
       [ 2.11349622, -0.81362671],
       [-1.14944531,  1.42679466],
       [-0.25955217,  0.15918783],
       [ 0.72921799, -1.40321127],
       [-1.14944531,  0.30658398],
       [-0.25955217,  0.80773086],
       [-1.74270741, -0.99050208],
       [ 2.21237324, -0.81362671],
       [-1.34719935, -1.37373205],
       [ 0.82809501,  1.39731543],
       [ 0.53146396,  1.75106617],
       [ 1.12472606,  2.10481691],
       [-0.85281426,  0.39502166],
       [-0.06179814,  2.1932546 ],
       [ 2.0146192 , -0.66623056],
       [ 2.11349622,  0.5424178 ],
       [-0.65506023, -0.04716677],
       [ 0.03707888, -0.54831365],
       [ 0.82809501, -0.31247982],
       [-0.75393725,  0.51293858],
       [ 0.92697203, -1.04946053],
       [ 1.02584904,  0.12970861],
       [ 0.23483291,  0.15918783],
       [ 0.33370993,  0.30658398],
       [ 0.43258695,  0.10022938],
       [-0.25955217, -1.31477359],
       [-0.55618322,  1.48575311],
       [ 0.63034098,  2.04585846],
       [-1.64383039,  0.5424178 ],
       [-0.35842918, -0.78414748],
       [ 1.12472606, -0.90206439],
       [-1.0505683 , -0.37143828],
       [-0.95169128, -0.96102285],
       [ 1.12472606,  0.57189703],
       [-0.95169128, -0.75466825],
       [-0.75393725, -1.55060742],
       [-1.54495338, -0.43039674],
       [ 1.81686517,  1.01408546],
       [-1.44607636, -1.46216973],
       [ 0.23483291, -0.37143828],
       [-1.34719935,  0.57189703],
       [ 0.03707888, -0.13560445],
       [ 0.23483291,  2.13429614],
       [ 1.42135711,  2.01637923],
       [-0.4573062 ,  1.27939852],
       [-1.14944531, -1.55060742],
       [ 1.02584904, -1.07893976],
       [ 2.0146192 ,  0.92564777]])

In [57]:
from sklearn import tree
#clf = tree.DecisionTreeClassifier(criterion='entropy', random_state=0)
clf = tree.DecisionTreeClassifier(criterion='gini')

In [58]:
clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [59]:
y_pred = clf.predict(x_test)

In [60]:
from sklearn.metrics import confusion_matrix

In [61]:
confusion_matrix(y_test, y_pred)

array([[54,  8],
       [11, 27]])

In [44]:
y_pred1 = clf.predict(x_test)

In [49]:
(43+21)/(43+21+11+5)

0.8

In [63]:
confusion_matrix(y_test, y_pred)

array([[54,  8],
       [11, 27]])

In [51]:
from sklearn.metrics import accuracy_score

In [55]:
from sklearn.metrics import classification_report

In [56]:
print(classification_report(y_test, y_pred1))

ValueError: Found input variables with inconsistent numbers of samples: [100, 80]

In [76]:
new_ind = np.array([[29, 95000]])
new_ind_sc = sc_x.transform(new_ind)
pred = clf.predict(new_ind_sc)

In [77]:
pred

array([1])