In [1]:
# Lasso

In [2]:
from sklearn.linear_model import Lasso
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [3]:
data = {
    'hours': [1, 2, 2, 3, 3, 4, 5, 5, 6, 7, 7, 8, 8, 9, 10],
    'attendence': [55, 60, 65, 62, 70, 72, 75, 80, 78, 82, 85, 88, 90, 92, 95],
    'assignmentscore': [40, 45, 50, 48, 55, 58, 62, 67, 65, 70, 74, 78, 80, 85, 90],
    'studentid': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
    'finalmarks': [35, 40, 43, 45, 50, 54, 60, 64, 66, 71, 74, 79, 82, 87, 92]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
x = df.iloc[:, [0, 1, 2, 3]]
y = df['finalmarks']

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=67)

In [10]:
model = make_pipeline(
    StandardScaler(),
    Lasso(alpha=0.1)
)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

In [11]:
lasso_model = model.named_steps["lasso"]

coeff_table = pd.DataFrame({
    'Predictor': x.columns,
    'Lasso Coefficient': lasso_model.coef_
})

In [12]:
coeff_table

         Predictor  Lasso Coefficient
0            hours           5.123353
1       attendence           1.711016
2  assignmentscore           5.385914
3        studentid           3.352072

In [14]:
print("Using Lasso model: ")
print("MAE: ", mean_absolute_error(y_test, y_pred))
print("MSE: ", mean_squared_error(y_test, y_pred))
print("R2: ", r2_score(y_test, y_pred))

Using Lasso model:
MAE:  0.7813096734528221
MSE:  0.6368696378731427
R2:  0.9984892391299793

In [ ]:
lasso_errors = {
    "MAE": [mean_absolute_error(y_test, y_pred)],
    "MSE": [mean_squared_error(y_test, y_pred)],
    "R2": [r2_score(y_test, y_pred)]
}

lasso_error_df = pd.DataFrame(lasso_errors)

In [20]:
lasso_error_df

       MAE      MSE        R2
0  0.78131  0.63687  0.998489

In [ ]:
# Apply Ordinary Linear Regre
# APlly ridge
# apply ridge cv
# apply lasso cv

Multiple Linear Regression

In [22]:
from sklearn.linear_model import LinearRegression
ml_model = LinearRegression()
ml_model.fit(x_train, y_train)
coeff_table_ml = pd.DataFrame({
    'Feature': x.columns,
    'Coefficients': ml_model.coef_
})
y_pred_ml = ml_model.predict(x_test)

ml_errors = {
    "MAE": [mean_absolute_error(y_test, y_pred_ml)],
    "MSE": [mean_squared_error(y_test, y_pred_ml)],
    "R2": [r2_score(y_test, y_pred_ml)]
}

ml_error_df = pd.DataFrame(ml_errors)

In [23]:
coeff_table_ml

           Feature  Coefficients
0            hours      2.155853
1       attendence      0.173804
2  assignmentscore      0.397225
3        studentid      0.867563

In [24]:
ml_error_df

        MAE      MSE        R2
0  0.771454  0.69634  0.998348

Ridge Regression Model

In [26]:
from sklearn.linear_model import Ridge
ridge_model = make_pipeline(
    StandardScaler(),
    Ridge(alpha=1.0)
)
ridge_model.fit(x_train, y_train)
coeff_table_ridge = pd.DataFrame({
    'Feature': x.columns,
    'Coefficients': ridge_model.named_steps['ridge'].coef_
})
y_pred_ridge = ridge_model.predict(x_test)

ridge_errors = {
    "MAE": [mean_absolute_error(y_test, y_pred_ridge)],
    "MSE": [mean_squared_error(y_test, y_pred_ridge)],
    "R2": [r2_score(y_test, y_pred_ridge)]
}

ridge_errors_df = pd.DataFrame(ridge_errors)

In [27]:
coeff_table_ridge

           Feature  Coefficients
0            hours      4.152618
1       attendence      3.501919
2  assignmentscore      3.802422
3        studentid      3.895448

In [28]:
ridge_errors_df

       MAE       MSE        R2
0  0.87777  0.783576  0.998141

Ridge CV

In [29]:
from sklearn.linear_model import RidgeCV
ridgecv_model = make_pipeline(
    StandardScaler(),
    RidgeCV(alphas=[0.01, 0.1, 1, 10, 100])
)
ridgecv_model.fit(x_train, y_train)
coeff_table_ridgecv = pd.DataFrame({
    'Feature': x.columns,
    'Coefficients': ridgecv_model.named_steps['ridgecv'].coef_
})
y_pred_ridgecv = ridgecv_model.predict(x_test)

ridgecv_errors = {
    "MAE": [mean_absolute_error(y_test, y_pred_ridgecv)],
    "MSE": [mean_squared_error(y_test, y_pred_ridgecv)],
    "R2": [r2_score(y_test, y_pred_ridgecv)]
}

ridgecv_errors_df = pd.DataFrame(ridgecv_errors)

In [30]:
coeff_table_ridgecv

           Feature  Coefficients
0            hours      4.886871
1       attendence      2.750891
2  assignmentscore      4.135600
3        studentid      3.869273

In [31]:
ridgecv_errors_df

        MAE       MSE        R2
0  0.768347  0.747214  0.998227

Lasso CV

In [32]:
from sklearn.linear_model import LassoCV
lassocv_model = make_pipeline(
    StandardScaler(),
    LassoCV(alphas=[0.01, 0.1, 1, 10, 100])
)
lassocv_model.fit(x_train, y_train)
coeff_table_lassocv = pd.DataFrame({
    'Feature': x.columns,
    'Coefficients': lassocv_model.named_steps['lassocv'].coef_
})
y_pred_lassocv = lassocv_model.predict(x_test)

lassocv_errors = {
    "MAE": [mean_absolute_error(y_test, y_pred_lassocv)],
    "MSE": [mean_squared_error(y_test, y_pred_lassocv)],
    "R2": [r2_score(y_test, y_pred_lassocv)]
}

lassocv_errors_df = pd.DataFrame(lassocv_errors)

In [33]:
coeff_table_lassocv

           Feature  Coefficients
0            hours      5.221974
1       attendence      1.807855
2  assignmentscore      5.352475
3        studentid      3.281668

In [34]:
lassocv_errors_df

        MAE       MSE        R2
0  0.776756  0.691913  0.998359

In [35]:
import pandas as pd

# Combine dictionary metrics
all_errors = {
    "Model": ["Multiple Linear","Ridge","RidgeCV", "Lasso", "Lasso CV"],
    "MAE": [
        mean_absolute_error(y_test, y_pred_ml),
        mean_absolute_error(y_test, y_pred_ridge),
        mean_absolute_error(y_test, y_pred_ridgecv),
        mean_absolute_error(y_test, y_pred),
        mean_absolute_error(y_test, y_pred_lassocv),
    ],
    "MSE": [
        mean_squared_error(y_test, y_pred_ml),
        mean_squared_error(y_test, y_pred_ridge),
        mean_squared_error(y_test, y_pred_ridgecv),
        mean_squared_error(y_test, y_pred),
        mean_squared_error(y_test, y_pred_lassocv),
    ],
    "R2": [
        r2_score(y_test, y_pred_ml),
        r2_score(y_test, y_pred_ridge),
        r2_score(y_test, y_pred_ridgecv),
        r2_score(y_test, y_pred),
        r2_score(y_test, y_pred_lassocv),
    ],
}

comparison_df = pd.DataFrame(all_errors).set_index("Model")
print(comparison_df)

                      MAE       MSE        R2
Model
Multiple Linear  0.771454  0.696340  0.998348
Ridge            0.877770  0.783576  0.998141
RidgeCV          0.768347  0.747214  0.998227
Lasso            0.781310  0.636870  0.998489
Lasso CV         0.776756  0.691913  0.998359